2025-09-15 03:09:31,623 10060 INFO ? odoo: Odoo version 17.0 
2025-09-15 03:09:31,623 10060 INFO ? odoo: Using configuration file at D:\Coding\seriously\learn-odoo\odoo\odoo.conf 
2025-09-15 03:09:31,623 10060 INFO ? odoo: addons paths: ['D:\\Coding\\seriously\\learn-odoo\\odoo\\odoo\\addons', 'd:\\coding\\seriously\\learn-odoo\\odoo\\data\\addons\\17.0', 'd:\\coding\\seriously\\learn-odoo\\odoo\\addons', 'd:\\coding\\seriously\\learn-odoo\\odoo\\custom_addons', 'd:\\coding\\seriously\\learn-odoo\\odoo\\odoo\\addons'] 
2025-09-15 03:09:31,624 10060 INFO ? odoo: database: odoo@localhost:5432 
2025-09-15 03:09:31,910 10060 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe 
2025-09-15 03:09:32,619 10060 WARNING ? odoo.service.server: 'watchdog' module not installed. Code autoreload feature is disabled 
2025-09-15 03:09:32,625 10060 INFO ? odoo.service.server: HTTP service (werkzeug) running on LAPTOP-O0EP5QSP:8069 
2025-09-15 03:09:32,708 10060 INFO ssi_odoo_db odoo.modules.loading: loading 1 modules... 
2025-09-15 03:09:32,717 10060 INFO ssi_odoo_db odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2025-09-15 03:09:32,753 10060 INFO ssi_odoo_db odoo.modules.loading: updating modules list 
2025-09-15 03:09:32,758 10060 INFO ssi_odoo_db odoo.addons.base.models.ir_module: ALLOW access to module.update_list on [] to user __system__ #1 via n/a 
2025-09-15 03:09:34,684 10060 INFO ssi_odoo_db odoo.addons.base.models.ir_module: ALLOW access to module.button_upgrade on ['TeknoParts Inventory – Spare-part HP'] to user __system__ #1 via n/a 
2025-09-15 03:09:34,684 10060 INFO ssi_odoo_db odoo.addons.base.models.ir_module: ALLOW access to module.update_list on ['TeknoParts Inventory – Spare-part HP'] to user __system__ #1 via n/a 
2025-09-15 03:09:35,218 10060 INFO ssi_odoo_db odoo.addons.base.models.ir_module: ALLOW access to module.button_install on [] to user __system__ #1 via n/a 
2025-09-15 03:09:35,267 10060 INFO ssi_odoo_db odoo.modules.loading: loading 72 modules... 
2025-09-15 03:09:36,153 10060 INFO ssi_odoo_db odoo.modules.loading: Loading module teknoparts_inventory (69/72) 
2025-09-15 03:09:36,384 10060 INFO ssi_odoo_db odoo.modules.registry: module teknoparts_inventory: creating or updating database tables 
2025-09-15 03:09:36,437 10060 INFO ssi_odoo_db odoo.models: Prepare computation of stock.picking.x_is_qc_required 
2025-09-15 03:09:36,630 10060 INFO ssi_odoo_db odoo.modules.loading: loading teknoparts_inventory/security/security.xml 
2025-09-15 03:09:36,704 10060 INFO ssi_odoo_db odoo.modules.loading: loading teknoparts_inventory/security/ir.model.access.csv 
2025-09-15 03:09:36,728 10060 WARNING ssi_odoo_db odoo.addons.base.models.ir_model: Rule tpart.part.public has no group, this is a deprecated feature. Every access-granting rule should specify a group. 
2025-09-15 03:09:36,728 10060 WARNING ssi_odoo_db odoo.addons.base.models.ir_model: Rule tpart.category.public has no group, this is a deprecated feature. Every access-granting rule should specify a group. 
2025-09-15 03:09:36,735 10060 INFO ssi_odoo_db odoo.modules.loading: loading teknoparts_inventory/security/part_rule.xml 
2025-09-15 03:09:36,749 10060 INFO ssi_odoo_db odoo.modules.loading: loading teknoparts_inventory/security/picking_rule.xml 
2025-09-15 03:09:36,759 10060 INFO ssi_odoo_db odoo.modules.loading: loading teknoparts_inventory/data/sequence.xml 
2025-09-15 03:09:36,764 10060 INFO ssi_odoo_db odoo.modules.loading: loading teknoparts_inventory/views/part_views.xml 
2025-09-15 03:09:36,807 10060 INFO ssi_odoo_db odoo.modules.loading: loading teknoparts_inventory/views/qc_check_views.xml 
2025-09-15 03:09:36,825 10060 INFO ssi_odoo_db odoo.modules.loading: loading teknoparts_inventory/views/inherit_existing.xml 
2025-09-15 03:09:36,861 10060 WARNING ssi_odoo_db odoo.modules.loading: Transient module states were reset 
2025-09-15 03:09:36,861 10060 ERROR ssi_odoo_db odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\cache.py", line 99, in lookup
    r = d[key]
        ~^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: ('ir.model.data', <function IrModelData._xmlid_lookup at 0x000001B7E1272980>, 'teknoparts_inventory.action_qc_check_wizard')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 434, in _tag_record
    f_val = _eval_xml(self, field, env)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 143, in _eval_xml
    +_process("".join(etree.tostring(n, encoding='unicode') for n in node))
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 132, in _process
    self.idref[id] = self.id_get(id)
                     ^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 546, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 552, in model_id_get
    return self.env['ir.model.data']._xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\addons\base\models\ir_model.py", line 2205, in _xmlid_to_res_model_res_id
    return self._xmlid_lookup(xmlid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\cache.py", line 104, in lookup
    value = d[key] = self.method(*args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\addons\base\models\ir_model.py", line 2198, in _xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: teknoparts_inventory.action_qc_check_wizard

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 577, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing file:/d:/coding/seriously/learn-odoo/odoo/custom_addons/teknoparts_inventory/views/inherit_existing.xml:22, somewhere inside
<record id="view_picking_form_inherit_qc" model="ir.ui.view">
    <field name="name">stock.picking.form.inherit.qc</field>
    <field name="model">stock.picking</field>
    <field name="inherit_id" ref="stock.view_picking_form"/>
    <field name="arch" type="xml">
      <data><header position="inside">
        <button name="%(action_qc_check_wizard)d" type="action" string="Create QC" class="oe_highlight" invisible="x_is_qc_required = False or state != 'done'"/>
      </header>
      <field name="origin" position="after">
        <field name="x_is_qc_required" invisible="1"/>
        <field name="x_qc_check_id" readonly="1"/>
      </field>
    </data></field>
  </record>
2025-09-15 03:09:36,872 10060 CRITICAL ssi_odoo_db odoo.service.server: Failed to initialize database `ssi_odoo_db`. 
Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\cache.py", line 99, in lookup
    r = d[key]
        ~^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: ('ir.model.data', <function IrModelData._xmlid_lookup at 0x000001B7E1272980>, 'teknoparts_inventory.action_qc_check_wizard')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 434, in _tag_record
    f_val = _eval_xml(self, field, env)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 143, in _eval_xml
    +_process("".join(etree.tostring(n, encoding='unicode') for n in node))
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 132, in _process
    self.idref[id] = self.id_get(id)
                     ^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 546, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 552, in model_id_get
    return self.env['ir.model.data']._xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\addons\base\models\ir_model.py", line 2205, in _xmlid_to_res_model_res_id
    return self._xmlid_lookup(xmlid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\cache.py", line 104, in lookup
    value = d[key] = self.method(*args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\addons\base\models\ir_model.py", line 2198, in _xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: teknoparts_inventory.action_qc_check_wizard

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\service\server.py", line 1369, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 577, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing file:/d:/coding/seriously/learn-odoo/odoo/custom_addons/teknoparts_inventory/views/inherit_existing.xml:22, somewhere inside
<record id="view_picking_form_inherit_qc" model="ir.ui.view">
    <field name="name">stock.picking.form.inherit.qc</field>
    <field name="model">stock.picking</field>
    <field name="inherit_id" ref="stock.view_picking_form"/>
    <field name="arch" type="xml">
      <data><header position="inside">
        <button name="%(action_qc_check_wizard)d" type="action" string="Create QC" class="oe_highlight" invisible="x_is_qc_required = False or state != 'done'"/>
      </header>
      <field name="origin" position="after">
        <field name="x_is_qc_required" invisible="1"/>
        <field name="x_qc_check_id" readonly="1"/>
      </field>
    </data></field>
  </record>
2025-09-15 03:09:38,438 10060 INFO ? odoo.modules.loading: loading 1 modules... 
2025-09-15 03:09:38,443 10060 INFO ? odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2025-09-15 03:09:38,453 10060 INFO ? odoo.modules.loading: loading 72 modules... 
2025-09-15 03:09:38,510 10060 INFO ? odoo.modules.loading: Loading module teknoparts_inventory (69/72) 
2025-09-15 03:09:38,852 10060 INFO ? odoo.modules.registry: module teknoparts_inventory: creating or updating database tables 
2025-09-15 03:09:38,885 10060 INFO ? odoo.models: Prepare computation of stock.picking.x_is_qc_required 
2025-09-15 03:09:39,028 10060 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/security.xml 
2025-09-15 03:09:39,103 10060 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/ir.model.access.csv 
2025-09-15 03:09:39,119 10060 WARNING ? odoo.addons.base.models.ir_model: Rule tpart.part.public has no group, this is a deprecated feature. Every access-granting rule should specify a group. 
2025-09-15 03:09:39,119 10060 WARNING ? odoo.addons.base.models.ir_model: Rule tpart.category.public has no group, this is a deprecated feature. Every access-granting rule should specify a group. 
2025-09-15 03:09:39,124 10060 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/part_rule.xml 
2025-09-15 03:09:39,132 10060 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/picking_rule.xml 
2025-09-15 03:09:39,139 10060 INFO ? odoo.modules.loading: loading teknoparts_inventory/data/sequence.xml 
2025-09-15 03:09:39,144 10060 INFO ? odoo.modules.loading: loading teknoparts_inventory/views/part_views.xml 
2025-09-15 03:09:39,177 10060 INFO ? odoo.modules.loading: loading teknoparts_inventory/views/qc_check_views.xml 
2025-09-15 03:09:39,196 10060 INFO ? odoo.modules.loading: loading teknoparts_inventory/views/inherit_existing.xml 
2025-09-15 03:09:39,236 10060 WARNING ? odoo.modules.loading: Transient module states were reset 
2025-09-15 03:09:39,236 10060 ERROR ? odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 87, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'ssi_odoo_db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\cache.py", line 99, in lookup
    r = d[key]
        ~^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: ('ir.model.data', <function IrModelData._xmlid_lookup at 0x000001B7E1272980>, 'teknoparts_inventory.action_qc_check_wizard')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 434, in _tag_record
    f_val = _eval_xml(self, field, env)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 143, in _eval_xml
    +_process("".join(etree.tostring(n, encoding='unicode') for n in node))
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 132, in _process
    self.idref[id] = self.id_get(id)
                     ^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 546, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 552, in model_id_get
    return self.env['ir.model.data']._xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\addons\base\models\ir_model.py", line 2205, in _xmlid_to_res_model_res_id
    return self._xmlid_lookup(xmlid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\cache.py", line 104, in lookup
    value = d[key] = self.method(*args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\addons\base\models\ir_model.py", line 2198, in _xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: teknoparts_inventory.action_qc_check_wizard

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 577, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing file:/d:/coding/seriously/learn-odoo/odoo/custom_addons/teknoparts_inventory/views/inherit_existing.xml:22, somewhere inside
<record id="view_picking_form_inherit_qc" model="ir.ui.view">
    <field name="name">stock.picking.form.inherit.qc</field>
    <field name="model">stock.picking</field>
    <field name="inherit_id" ref="stock.view_picking_form"/>
    <field name="arch" type="xml">
      <data><header position="inside">
        <button name="%(action_qc_check_wizard)d" type="action" string="Create QC" class="oe_highlight" invisible="x_is_qc_required = False or state != 'done'"/>
      </header>
      <field name="origin" position="after">
        <field name="x_is_qc_required" invisible="1"/>
        <field name="x_qc_check_id" readonly="1"/>
      </field>
    </data></field>
  </record>
2025-09-15 03:09:39,239 10060 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 87, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'ssi_odoo_db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\cache.py", line 99, in lookup
    r = d[key]
        ~^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: ('ir.model.data', <function IrModelData._xmlid_lookup at 0x000001B7E1272980>, 'teknoparts_inventory.action_qc_check_wizard')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 434, in _tag_record
    f_val = _eval_xml(self, field, env)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 143, in _eval_xml
    +_process("".join(etree.tostring(n, encoding='unicode') for n in node))
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 132, in _process
    self.idref[id] = self.id_get(id)
                     ^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 546, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 552, in model_id_get
    return self.env['ir.model.data']._xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\addons\base\models\ir_model.py", line 2205, in _xmlid_to_res_model_res_id
    return self._xmlid_lookup(xmlid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\cache.py", line 104, in lookup
    value = d[key] = self.method(*args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\addons\base\models\ir_model.py", line 2198, in _xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: teknoparts_inventory.action_qc_check_wizard

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\http.py", line 2396, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\http.py", line 1949, in _serve_db
    self.registry = Registry(self.db).check_signaling()
                    ^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 89, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 577, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing file:/d:/coding/seriously/learn-odoo/odoo/custom_addons/teknoparts_inventory/views/inherit_existing.xml:22, somewhere inside
<record id="view_picking_form_inherit_qc" model="ir.ui.view">
    <field name="name">stock.picking.form.inherit.qc</field>
    <field name="model">stock.picking</field>
    <field name="inherit_id" ref="stock.view_picking_form"/>
    <field name="arch" type="xml">
      <data><header position="inside">
        <button name="%(action_qc_check_wizard)d" type="action" string="Create QC" class="oe_highlight" invisible="x_is_qc_required = False or state != 'done'"/>
      </header>
      <field name="origin" position="after">
        <field name="x_is_qc_required" invisible="1"/>
        <field name="x_qc_check_id" readonly="1"/>
      </field>
    </data></field>
  </record>
2025-09-15 03:09:39,243 10060 INFO ? werkzeug: 127.0.0.1 - - [15/Sep/2025 03:09:39] "GET /web HTTP/1.1" 500 - 412 0.190 0.622
2025-09-15 03:09:39,317 10060 INFO ? odoo.modules.loading: loading 1 modules... 
2025-09-15 03:09:39,326 10060 INFO ? odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2025-09-15 03:09:39,337 10060 INFO ? odoo.modules.loading: loading 72 modules... 
2025-09-15 03:09:39,385 10060 INFO ? odoo.modules.loading: Loading module teknoparts_inventory (69/72) 
2025-09-15 03:09:39,658 10060 INFO ? odoo.modules.registry: module teknoparts_inventory: creating or updating database tables 
2025-09-15 03:09:39,694 10060 INFO ? odoo.models: Prepare computation of stock.picking.x_is_qc_required 
2025-09-15 03:09:39,827 10060 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/security.xml 
2025-09-15 03:09:39,895 10060 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/ir.model.access.csv 
2025-09-15 03:09:39,908 10060 WARNING ? odoo.addons.base.models.ir_model: Rule tpart.part.public has no group, this is a deprecated feature. Every access-granting rule should specify a group. 
2025-09-15 03:09:39,908 10060 WARNING ? odoo.addons.base.models.ir_model: Rule tpart.category.public has no group, this is a deprecated feature. Every access-granting rule should specify a group. 
2025-09-15 03:09:39,912 10060 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/part_rule.xml 
2025-09-15 03:09:39,920 10060 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/picking_rule.xml 
2025-09-15 03:09:39,927 10060 INFO ? odoo.modules.loading: loading teknoparts_inventory/data/sequence.xml 
2025-09-15 03:09:39,931 10060 INFO ? odoo.modules.loading: loading teknoparts_inventory/views/part_views.xml 
2025-09-15 03:09:39,964 10060 INFO ? odoo.modules.loading: loading teknoparts_inventory/views/qc_check_views.xml 
2025-09-15 03:09:39,983 10060 INFO ? odoo.modules.loading: loading teknoparts_inventory/views/inherit_existing.xml 
2025-09-15 03:09:40,019 10060 WARNING ? odoo.modules.loading: Transient module states were reset 
2025-09-15 03:09:40,019 10060 ERROR ? odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 87, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'ssi_odoo_db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\cache.py", line 99, in lookup
    r = d[key]
        ~^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: ('ir.model.data', <function IrModelData._xmlid_lookup at 0x000001B7E1272980>, 'teknoparts_inventory.action_qc_check_wizard')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 434, in _tag_record
    f_val = _eval_xml(self, field, env)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 143, in _eval_xml
    +_process("".join(etree.tostring(n, encoding='unicode') for n in node))
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 132, in _process
    self.idref[id] = self.id_get(id)
                     ^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 546, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 552, in model_id_get
    return self.env['ir.model.data']._xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\addons\base\models\ir_model.py", line 2205, in _xmlid_to_res_model_res_id
    return self._xmlid_lookup(xmlid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\cache.py", line 104, in lookup
    value = d[key] = self.method(*args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\addons\base\models\ir_model.py", line 2198, in _xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: teknoparts_inventory.action_qc_check_wizard

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 577, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing file:/d:/coding/seriously/learn-odoo/odoo/custom_addons/teknoparts_inventory/views/inherit_existing.xml:22, somewhere inside
<record id="view_picking_form_inherit_qc" model="ir.ui.view">
    <field name="name">stock.picking.form.inherit.qc</field>
    <field name="model">stock.picking</field>
    <field name="inherit_id" ref="stock.view_picking_form"/>
    <field name="arch" type="xml">
      <data><header position="inside">
        <button name="%(action_qc_check_wizard)d" type="action" string="Create QC" class="oe_highlight" invisible="x_is_qc_required = False or state != 'done'"/>
      </header>
      <field name="origin" position="after">
        <field name="x_is_qc_required" invisible="1"/>
        <field name="x_qc_check_id" readonly="1"/>
      </field>
    </data></field>
  </record>
2025-09-15 03:09:40,022 10060 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 87, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'ssi_odoo_db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\cache.py", line 99, in lookup
    r = d[key]
        ~^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: ('ir.model.data', <function IrModelData._xmlid_lookup at 0x000001B7E1272980>, 'teknoparts_inventory.action_qc_check_wizard')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 434, in _tag_record
    f_val = _eval_xml(self, field, env)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 143, in _eval_xml
    +_process("".join(etree.tostring(n, encoding='unicode') for n in node))
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 132, in _process
    self.idref[id] = self.id_get(id)
                     ^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 546, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 552, in model_id_get
    return self.env['ir.model.data']._xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\addons\base\models\ir_model.py", line 2205, in _xmlid_to_res_model_res_id
    return self._xmlid_lookup(xmlid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\cache.py", line 104, in lookup
    value = d[key] = self.method(*args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\addons\base\models\ir_model.py", line 2198, in _xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: teknoparts_inventory.action_qc_check_wizard

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\http.py", line 2396, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\http.py", line 1949, in _serve_db
    self.registry = Registry(self.db).check_signaling()
                    ^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 89, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 577, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing file:/d:/coding/seriously/learn-odoo/odoo/custom_addons/teknoparts_inventory/views/inherit_existing.xml:22, somewhere inside
<record id="view_picking_form_inherit_qc" model="ir.ui.view">
    <field name="name">stock.picking.form.inherit.qc</field>
    <field name="model">stock.picking</field>
    <field name="inherit_id" ref="stock.view_picking_form"/>
    <field name="arch" type="xml">
      <data><header position="inside">
        <button name="%(action_qc_check_wizard)d" type="action" string="Create QC" class="oe_highlight" invisible="x_is_qc_required = False or state != 'done'"/>
      </header>
      <field name="origin" position="after">
        <field name="x_is_qc_required" invisible="1"/>
        <field name="x_qc_check_id" readonly="1"/>
      </field>
    </data></field>
  </record>
2025-09-15 03:09:40,025 10060 INFO ? werkzeug: 127.0.0.1 - - [15/Sep/2025 03:09:40] "GET /favicon.ico HTTP/1.1" 500 - 412 0.185 0.530
2025-09-15 03:09:41,038 10060 INFO ? odoo.modules.loading: loading 1 modules... 
2025-09-15 03:09:41,044 10060 INFO ? odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2025-09-15 03:09:41,050 10060 INFO ? odoo.modules.loading: loading 72 modules... 
2025-09-15 03:09:41,092 10060 INFO ? odoo.modules.loading: Loading module teknoparts_inventory (69/72) 
2025-09-15 03:09:41,435 10060 INFO ? odoo.modules.registry: module teknoparts_inventory: creating or updating database tables 
2025-09-15 03:09:41,471 10060 INFO ? odoo.models: Prepare computation of stock.picking.x_is_qc_required 
2025-09-15 03:09:41,607 10060 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/security.xml 
2025-09-15 03:09:41,673 10060 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/ir.model.access.csv 
2025-09-15 03:09:41,689 10060 WARNING ? odoo.addons.base.models.ir_model: Rule tpart.part.public has no group, this is a deprecated feature. Every access-granting rule should specify a group. 
2025-09-15 03:09:41,689 10060 WARNING ? odoo.addons.base.models.ir_model: Rule tpart.category.public has no group, this is a deprecated feature. Every access-granting rule should specify a group. 
2025-09-15 03:09:41,693 10060 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/part_rule.xml 
2025-09-15 03:09:41,700 10060 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/picking_rule.xml 
2025-09-15 03:09:41,706 10060 INFO ? odoo.modules.loading: loading teknoparts_inventory/data/sequence.xml 
2025-09-15 03:09:41,710 10060 INFO ? odoo.modules.loading: loading teknoparts_inventory/views/part_views.xml 
2025-09-15 03:09:41,741 10060 INFO ? odoo.modules.loading: loading teknoparts_inventory/views/qc_check_views.xml 
2025-09-15 03:09:41,762 10060 INFO ? odoo.modules.loading: loading teknoparts_inventory/views/inherit_existing.xml 
2025-09-15 03:09:41,792 10060 WARNING ? odoo.modules.loading: Transient module states were reset 
2025-09-15 03:09:41,793 10060 ERROR ? odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 87, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'ssi_odoo_db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\cache.py", line 99, in lookup
    r = d[key]
        ~^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: ('ir.model.data', <function IrModelData._xmlid_lookup at 0x000001B7E1272980>, 'teknoparts_inventory.action_qc_check_wizard')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 434, in _tag_record
    f_val = _eval_xml(self, field, env)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 143, in _eval_xml
    +_process("".join(etree.tostring(n, encoding='unicode') for n in node))
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 132, in _process
    self.idref[id] = self.id_get(id)
                     ^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 546, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 552, in model_id_get
    return self.env['ir.model.data']._xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\addons\base\models\ir_model.py", line 2205, in _xmlid_to_res_model_res_id
    return self._xmlid_lookup(xmlid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\cache.py", line 104, in lookup
    value = d[key] = self.method(*args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\addons\base\models\ir_model.py", line 2198, in _xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: teknoparts_inventory.action_qc_check_wizard

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 577, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing file:/d:/coding/seriously/learn-odoo/odoo/custom_addons/teknoparts_inventory/views/inherit_existing.xml:22, somewhere inside
<record id="view_picking_form_inherit_qc" model="ir.ui.view">
    <field name="name">stock.picking.form.inherit.qc</field>
    <field name="model">stock.picking</field>
    <field name="inherit_id" ref="stock.view_picking_form"/>
    <field name="arch" type="xml">
      <data><header position="inside">
        <button name="%(action_qc_check_wizard)d" type="action" string="Create QC" class="oe_highlight" invisible="x_is_qc_required = False or state != 'done'"/>
      </header>
      <field name="origin" position="after">
        <field name="x_is_qc_required" invisible="1"/>
        <field name="x_qc_check_id" readonly="1"/>
      </field>
    </data></field>
  </record>
2025-09-15 03:09:41,795 10060 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 87, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'ssi_odoo_db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\cache.py", line 99, in lookup
    r = d[key]
        ~^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: ('ir.model.data', <function IrModelData._xmlid_lookup at 0x000001B7E1272980>, 'teknoparts_inventory.action_qc_check_wizard')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 434, in _tag_record
    f_val = _eval_xml(self, field, env)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 143, in _eval_xml
    +_process("".join(etree.tostring(n, encoding='unicode') for n in node))
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 132, in _process
    self.idref[id] = self.id_get(id)
                     ^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 546, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 552, in model_id_get
    return self.env['ir.model.data']._xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\addons\base\models\ir_model.py", line 2205, in _xmlid_to_res_model_res_id
    return self._xmlid_lookup(xmlid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\cache.py", line 104, in lookup
    value = d[key] = self.method(*args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\addons\base\models\ir_model.py", line 2198, in _xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: teknoparts_inventory.action_qc_check_wizard

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\http.py", line 2396, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\http.py", line 1949, in _serve_db
    self.registry = Registry(self.db).check_signaling()
                    ^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 89, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 577, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing file:/d:/coding/seriously/learn-odoo/odoo/custom_addons/teknoparts_inventory/views/inherit_existing.xml:22, somewhere inside
<record id="view_picking_form_inherit_qc" model="ir.ui.view">
    <field name="name">stock.picking.form.inherit.qc</field>
    <field name="model">stock.picking</field>
    <field name="inherit_id" ref="stock.view_picking_form"/>
    <field name="arch" type="xml">
      <data><header position="inside">
        <button name="%(action_qc_check_wizard)d" type="action" string="Create QC" class="oe_highlight" invisible="x_is_qc_required = False or state != 'done'"/>
      </header>
      <field name="origin" position="after">
        <field name="x_is_qc_required" invisible="1"/>
        <field name="x_qc_check_id" readonly="1"/>
      </field>
    </data></field>
  </record>
2025-09-15 03:09:41,798 10060 INFO ? werkzeug: 127.0.0.1 - - [15/Sep/2025 03:09:41] "GET /web/service-worker.js HTTP/1.1" 500 - 412 0.185 0.580
2025-09-15 03:14:30,405 10060 INFO ssi_odoo_db odoo.service.server: Initiating shutdown 
2025-09-15 03:14:30,406 10060 INFO ssi_odoo_db odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2025-09-15 03:14:30,453 10060 INFO ssi_odoo_db odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 3 connections  
2025-09-15 03:14:38,905 11600 INFO ? odoo: Odoo version 17.0 
2025-09-15 03:14:38,906 11600 INFO ? odoo: Using configuration file at D:\Coding\seriously\learn-odoo\odoo\odoo.conf 
2025-09-15 03:14:38,906 11600 INFO ? odoo: addons paths: ['D:\\Coding\\seriously\\learn-odoo\\odoo\\odoo\\addons', 'd:\\coding\\seriously\\learn-odoo\\odoo\\data\\addons\\17.0', 'd:\\coding\\seriously\\learn-odoo\\odoo\\addons', 'd:\\coding\\seriously\\learn-odoo\\odoo\\custom_addons', 'd:\\coding\\seriously\\learn-odoo\\odoo\\odoo\\addons'] 
2025-09-15 03:14:38,906 11600 INFO ? odoo: database: odoo@localhost:5432 
2025-09-15 03:14:39,229 11600 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe 
2025-09-15 03:14:39,497 11600 WARNING ? odoo.service.server: 'watchdog' module not installed. Code autoreload feature is disabled 
2025-09-15 03:14:39,506 11600 INFO ? odoo.service.server: HTTP service (werkzeug) running on LAPTOP-O0EP5QSP:8069 
2025-09-15 03:14:39,563 11600 INFO ssi_odoo_db odoo.modules.loading: loading 1 modules... 
2025-09-15 03:14:39,569 11600 INFO ssi_odoo_db odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2025-09-15 03:14:39,591 11600 INFO ssi_odoo_db odoo.modules.loading: updating modules list 
2025-09-15 03:14:39,596 11600 INFO ssi_odoo_db odoo.addons.base.models.ir_module: ALLOW access to module.update_list on [] to user __system__ #1 via n/a 
2025-09-15 03:14:41,029 11600 INFO ssi_odoo_db odoo.addons.base.models.ir_module: ALLOW access to module.button_upgrade on ['TeknoParts Inventory – Spare-part HP'] to user __system__ #1 via n/a 
2025-09-15 03:14:41,030 11600 INFO ssi_odoo_db odoo.addons.base.models.ir_module: ALLOW access to module.update_list on ['TeknoParts Inventory – Spare-part HP'] to user __system__ #1 via n/a 
2025-09-15 03:14:41,589 11600 INFO ssi_odoo_db odoo.addons.base.models.ir_module: ALLOW access to module.button_install on [] to user __system__ #1 via n/a 
2025-09-15 03:14:41,675 11600 INFO ssi_odoo_db odoo.modules.loading: loading 72 modules... 
2025-09-15 03:14:43,026 11600 INFO ssi_odoo_db odoo.modules.loading: Loading module teknoparts_inventory (69/72) 
2025-09-15 03:14:43,337 11600 INFO ssi_odoo_db odoo.modules.registry: module teknoparts_inventory: creating or updating database tables 
2025-09-15 03:14:43,413 11600 INFO ssi_odoo_db odoo.models: Prepare computation of stock.picking.x_is_qc_required 
2025-09-15 03:14:43,864 11600 INFO ssi_odoo_db odoo.modules.loading: loading teknoparts_inventory/security/security.xml 
2025-09-15 03:14:43,958 11600 INFO ssi_odoo_db odoo.modules.loading: loading teknoparts_inventory/security/ir.model.access.csv 
2025-09-15 03:14:43,989 11600 WARNING ssi_odoo_db odoo.addons.base.models.ir_model: Rule tpart.part.public has no group, this is a deprecated feature. Every access-granting rule should specify a group. 
2025-09-15 03:14:43,989 11600 WARNING ssi_odoo_db odoo.addons.base.models.ir_model: Rule tpart.category.public has no group, this is a deprecated feature. Every access-granting rule should specify a group. 
2025-09-15 03:14:43,999 11600 INFO ssi_odoo_db odoo.modules.loading: loading teknoparts_inventory/security/part_rule.xml 
2025-09-15 03:14:44,021 11600 INFO ssi_odoo_db odoo.modules.loading: loading teknoparts_inventory/security/picking_rule.xml 
2025-09-15 03:14:44,037 11600 INFO ssi_odoo_db odoo.modules.loading: loading teknoparts_inventory/data/sequence.xml 
2025-09-15 03:14:44,044 11600 INFO ssi_odoo_db odoo.modules.loading: loading teknoparts_inventory/wizard/qc_check_wizard.xml 
2025-09-15 03:14:44,066 11600 INFO ssi_odoo_db odoo.modules.loading: loading teknoparts_inventory/views/part_views.xml 
2025-09-15 03:14:44,121 11600 INFO ssi_odoo_db odoo.modules.loading: loading teknoparts_inventory/views/qc_check_views.xml 
2025-09-15 03:14:44,142 11600 INFO ssi_odoo_db odoo.modules.loading: loading teknoparts_inventory/views/inherit_existing.xml 
2025-09-15 03:14:44,241 11600 WARNING ssi_odoo_db odoo.modules.loading: Transient module states were reset 
2025-09-15 03:14:44,241 11600 ERROR ssi_odoo_db odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 575, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo.tools.convert.ParseError: while parsing file:/d:/coding/seriously/learn-odoo/odoo/custom_addons/teknoparts_inventory/views/inherit_existing.xml:22
Error while validating view near:

<form string="Transfer" js_class="picking_form">
                <field name="country_code" invisible="1"/>
                <field name="is_locked" invisible="1"/>
                <field name="show_check_availability" invisible="1"/>
                <field name="show_lots_text" invisible="1"/>

Invalid modifier 'invisible': "x_is_qc_required = False or state != 'done'"
invalid syntax (<unknown>, line 1)

View error context:
{'file': 'd:\\coding\\seriously\\learn-odoo\\odoo\\custom_addons\\teknoparts_inventory\\views\\inherit_existing.xml',
 'line': 3,
 'name': 'stock.picking.form.inherit.qc',
 'view': ir.ui.view(1410,),
 'view.model': 'stock.picking',
 'view.parent': ir.ui.view(1063,),
 'xmlid': 'view_picking_form_inherit_qc'}

2025-09-15 03:14:44,244 11600 CRITICAL ssi_odoo_db odoo.service.server: Failed to initialize database `ssi_odoo_db`. 
Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\service\server.py", line 1369, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 575, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo.tools.convert.ParseError: while parsing file:/d:/coding/seriously/learn-odoo/odoo/custom_addons/teknoparts_inventory/views/inherit_existing.xml:22
Error while validating view near:

<form string="Transfer" js_class="picking_form">
                <field name="country_code" invisible="1"/>
                <field name="is_locked" invisible="1"/>
                <field name="show_check_availability" invisible="1"/>
                <field name="show_lots_text" invisible="1"/>

Invalid modifier 'invisible': "x_is_qc_required = False or state != 'done'"
invalid syntax (<unknown>, line 1)

View error context:
{'file': 'd:\\coding\\seriously\\learn-odoo\\odoo\\custom_addons\\teknoparts_inventory\\views\\inherit_existing.xml',
 'line': 3,
 'name': 'stock.picking.form.inherit.qc',
 'view': ir.ui.view(1410,),
 'view.model': 'stock.picking',
 'view.parent': ir.ui.view(1063,),
 'xmlid': 'view_picking_form_inherit_qc'}

2025-09-15 03:15:18,130 11600 INFO ? odoo.modules.loading: loading 1 modules... 
2025-09-15 03:15:18,135 11600 INFO ? odoo.modules.loading: 1 modules loaded in 0.00s, 0 queries (+0 extra) 
2025-09-15 03:15:18,142 11600 INFO ? odoo.modules.loading: loading 72 modules... 
2025-09-15 03:15:18,180 11600 INFO ? odoo.modules.loading: Loading module teknoparts_inventory (69/72) 
2025-09-15 03:15:18,471 11600 INFO ? odoo.modules.registry: module teknoparts_inventory: creating or updating database tables 
2025-09-15 03:15:18,507 11600 INFO ? odoo.models: Prepare computation of stock.picking.x_is_qc_required 
2025-09-15 03:15:18,637 11600 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/security.xml 
2025-09-15 03:15:18,696 11600 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/ir.model.access.csv 
2025-09-15 03:15:18,713 11600 WARNING ? odoo.addons.base.models.ir_model: Rule tpart.part.public has no group, this is a deprecated feature. Every access-granting rule should specify a group. 
2025-09-15 03:15:18,713 11600 WARNING ? odoo.addons.base.models.ir_model: Rule tpart.category.public has no group, this is a deprecated feature. Every access-granting rule should specify a group. 
2025-09-15 03:15:18,717 11600 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/part_rule.xml 
2025-09-15 03:15:18,724 11600 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/picking_rule.xml 
2025-09-15 03:15:18,731 11600 INFO ? odoo.modules.loading: loading teknoparts_inventory/data/sequence.xml 
2025-09-15 03:15:18,735 11600 INFO ? odoo.modules.loading: loading teknoparts_inventory/wizard/qc_check_wizard.xml 
2025-09-15 03:15:18,746 11600 INFO ? odoo.modules.loading: loading teknoparts_inventory/views/part_views.xml 
2025-09-15 03:15:18,779 11600 INFO ? odoo.modules.loading: loading teknoparts_inventory/views/qc_check_views.xml 
2025-09-15 03:15:18,798 11600 INFO ? odoo.modules.loading: loading teknoparts_inventory/views/inherit_existing.xml 
2025-09-15 03:15:18,857 11600 WARNING ? odoo.modules.loading: Transient module states were reset 
2025-09-15 03:15:18,858 11600 ERROR ? odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 575, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo.tools.convert.ParseError: while parsing file:/d:/coding/seriously/learn-odoo/odoo/custom_addons/teknoparts_inventory/views/inherit_existing.xml:22
Error while validating view near:

<form string="Transfer" js_class="picking_form">
                <field name="country_code" invisible="1"/>
                <field name="is_locked" invisible="1"/>
                <field name="show_check_availability" invisible="1"/>
                <field name="show_lots_text" invisible="1"/>

Invalid modifier 'invisible': "x_is_qc_required = False or state != 'done'"
invalid syntax (<unknown>, line 1)

View error context:
{'file': 'd:\\coding\\seriously\\learn-odoo\\odoo\\custom_addons\\teknoparts_inventory\\views\\inherit_existing.xml',
 'line': 3,
 'name': 'stock.picking.form.inherit.qc',
 'view': ir.ui.view(1413,),
 'view.model': 'stock.picking',
 'view.parent': ir.ui.view(1063,),
 'xmlid': 'view_picking_form_inherit_qc'}

2025-09-15 03:15:18,859 11600 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\http.py", line 2396, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\http.py", line 1949, in _serve_db
    self.registry = Registry(self.db).check_signaling()
                    ^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 89, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 575, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo.tools.convert.ParseError: while parsing file:/d:/coding/seriously/learn-odoo/odoo/custom_addons/teknoparts_inventory/views/inherit_existing.xml:22
Error while validating view near:

<form string="Transfer" js_class="picking_form">
                <field name="country_code" invisible="1"/>
                <field name="is_locked" invisible="1"/>
                <field name="show_check_availability" invisible="1"/>
                <field name="show_lots_text" invisible="1"/>

Invalid modifier 'invisible': "x_is_qc_required = False or state != 'done'"
invalid syntax (<unknown>, line 1)

View error context:
{'file': 'd:\\coding\\seriously\\learn-odoo\\odoo\\custom_addons\\teknoparts_inventory\\views\\inherit_existing.xml',
 'line': 3,
 'name': 'stock.picking.form.inherit.qc',
 'view': ir.ui.view(1413,),
 'view.model': 'stock.picking',
 'view.parent': ir.ui.view(1063,),
 'xmlid': 'view_picking_form_inherit_qc'}

2025-09-15 03:15:18,862 11600 INFO ? werkzeug: 127.0.0.1 - - [15/Sep/2025 03:15:18] "GET / HTTP/1.1" 500 - 434 0.235 0.501
2025-09-15 03:15:18,874 11600 INFO ? odoo.modules.loading: loading 1 modules... 
2025-09-15 03:15:18,881 11600 INFO ? odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2025-09-15 03:15:18,891 11600 INFO ? odoo.modules.loading: loading 72 modules... 
2025-09-15 03:15:18,926 11600 INFO ? odoo.modules.loading: Loading module teknoparts_inventory (69/72) 
2025-09-15 03:15:19,145 11600 INFO ? odoo.modules.registry: module teknoparts_inventory: creating or updating database tables 
2025-09-15 03:15:19,181 11600 INFO ? odoo.models: Prepare computation of stock.picking.x_is_qc_required 
2025-09-15 03:15:19,315 11600 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/security.xml 
2025-09-15 03:15:19,376 11600 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/ir.model.access.csv 
2025-09-15 03:15:19,392 11600 WARNING ? odoo.addons.base.models.ir_model: Rule tpart.part.public has no group, this is a deprecated feature. Every access-granting rule should specify a group. 
2025-09-15 03:15:19,392 11600 WARNING ? odoo.addons.base.models.ir_model: Rule tpart.category.public has no group, this is a deprecated feature. Every access-granting rule should specify a group. 
2025-09-15 03:15:19,397 11600 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/part_rule.xml 
2025-09-15 03:15:19,406 11600 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/picking_rule.xml 
2025-09-15 03:15:19,415 11600 INFO ? odoo.modules.loading: loading teknoparts_inventory/data/sequence.xml 
2025-09-15 03:15:19,420 11600 INFO ? odoo.modules.loading: loading teknoparts_inventory/wizard/qc_check_wizard.xml 
2025-09-15 03:15:19,432 11600 INFO ? odoo.modules.loading: loading teknoparts_inventory/views/part_views.xml 
2025-09-15 03:15:19,469 11600 INFO ? odoo.modules.loading: loading teknoparts_inventory/views/qc_check_views.xml 
2025-09-15 03:15:19,494 11600 INFO ? odoo.modules.loading: loading teknoparts_inventory/views/inherit_existing.xml 
2025-09-15 03:15:19,549 11600 WARNING ? odoo.modules.loading: Transient module states were reset 
2025-09-15 03:15:19,549 11600 ERROR ? odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 575, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo.tools.convert.ParseError: while parsing file:/d:/coding/seriously/learn-odoo/odoo/custom_addons/teknoparts_inventory/views/inherit_existing.xml:22
Error while validating view near:

<form string="Transfer" js_class="picking_form">
                <field name="country_code" invisible="1"/>
                <field name="is_locked" invisible="1"/>
                <field name="show_check_availability" invisible="1"/>
                <field name="show_lots_text" invisible="1"/>

Invalid modifier 'invisible': "x_is_qc_required = False or state != 'done'"
invalid syntax (<unknown>, line 1)

View error context:
{'file': 'd:\\coding\\seriously\\learn-odoo\\odoo\\custom_addons\\teknoparts_inventory\\views\\inherit_existing.xml',
 'line': 3,
 'name': 'stock.picking.form.inherit.qc',
 'view': ir.ui.view(1416,),
 'view.model': 'stock.picking',
 'view.parent': ir.ui.view(1063,),
 'xmlid': 'view_picking_form_inherit_qc'}

2025-09-15 03:15:19,550 11600 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\http.py", line 2396, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\http.py", line 1949, in _serve_db
    self.registry = Registry(self.db).check_signaling()
                    ^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 89, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 575, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo.tools.convert.ParseError: while parsing file:/d:/coding/seriously/learn-odoo/odoo/custom_addons/teknoparts_inventory/views/inherit_existing.xml:22
Error while validating view near:

<form string="Transfer" js_class="picking_form">
                <field name="country_code" invisible="1"/>
                <field name="is_locked" invisible="1"/>
                <field name="show_check_availability" invisible="1"/>
                <field name="show_lots_text" invisible="1"/>

Invalid modifier 'invisible': "x_is_qc_required = False or state != 'done'"
invalid syntax (<unknown>, line 1)

View error context:
{'file': 'd:\\coding\\seriously\\learn-odoo\\odoo\\custom_addons\\teknoparts_inventory\\views\\inherit_existing.xml',
 'line': 3,
 'name': 'stock.picking.form.inherit.qc',
 'view': ir.ui.view(1416,),
 'view.model': 'stock.picking',
 'view.parent': ir.ui.view(1063,),
 'xmlid': 'view_picking_form_inherit_qc'}

2025-09-15 03:15:19,552 11600 INFO ? werkzeug: 127.0.0.1 - - [15/Sep/2025 03:15:19] "GET / HTTP/1.1" 500 - 434 0.224 0.460
2025-09-15 03:15:19,631 11600 INFO ? odoo.modules.loading: loading 1 modules... 
2025-09-15 03:15:19,641 11600 INFO ? odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2025-09-15 03:15:19,652 11600 INFO ? odoo.modules.loading: loading 72 modules... 
2025-09-15 03:15:19,708 11600 INFO ? odoo.modules.loading: Loading module teknoparts_inventory (69/72) 
2025-09-15 03:15:20,020 11600 INFO ? odoo.modules.registry: module teknoparts_inventory: creating or updating database tables 
2025-09-15 03:15:20,054 11600 INFO ? odoo.models: Prepare computation of stock.picking.x_is_qc_required 
2025-09-15 03:15:20,191 11600 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/security.xml 
2025-09-15 03:15:20,252 11600 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/ir.model.access.csv 
2025-09-15 03:15:20,264 11600 WARNING ? odoo.addons.base.models.ir_model: Rule tpart.part.public has no group, this is a deprecated feature. Every access-granting rule should specify a group. 
2025-09-15 03:15:20,264 11600 WARNING ? odoo.addons.base.models.ir_model: Rule tpart.category.public has no group, this is a deprecated feature. Every access-granting rule should specify a group. 
2025-09-15 03:15:20,268 11600 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/part_rule.xml 
2025-09-15 03:15:20,273 11600 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/picking_rule.xml 
2025-09-15 03:15:20,280 11600 INFO ? odoo.modules.loading: loading teknoparts_inventory/data/sequence.xml 
2025-09-15 03:15:20,283 11600 INFO ? odoo.modules.loading: loading teknoparts_inventory/wizard/qc_check_wizard.xml 
2025-09-15 03:15:20,291 11600 INFO ? odoo.modules.loading: loading teknoparts_inventory/views/part_views.xml 
2025-09-15 03:15:20,319 11600 INFO ? odoo.modules.loading: loading teknoparts_inventory/views/qc_check_views.xml 
2025-09-15 03:15:20,336 11600 INFO ? odoo.modules.loading: loading teknoparts_inventory/views/inherit_existing.xml 
2025-09-15 03:15:20,386 11600 WARNING ? odoo.modules.loading: Transient module states were reset 
2025-09-15 03:15:20,386 11600 ERROR ? odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 575, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo.tools.convert.ParseError: while parsing file:/d:/coding/seriously/learn-odoo/odoo/custom_addons/teknoparts_inventory/views/inherit_existing.xml:22
Error while validating view near:

<form string="Transfer" js_class="picking_form">
                <field name="country_code" invisible="1"/>
                <field name="is_locked" invisible="1"/>
                <field name="show_check_availability" invisible="1"/>
                <field name="show_lots_text" invisible="1"/>

Invalid modifier 'invisible': "x_is_qc_required = False or state != 'done'"
invalid syntax (<unknown>, line 1)

View error context:
{'file': 'd:\\coding\\seriously\\learn-odoo\\odoo\\custom_addons\\teknoparts_inventory\\views\\inherit_existing.xml',
 'line': 3,
 'name': 'stock.picking.form.inherit.qc',
 'view': ir.ui.view(1419,),
 'view.model': 'stock.picking',
 'view.parent': ir.ui.view(1063,),
 'xmlid': 'view_picking_form_inherit_qc'}

2025-09-15 03:15:20,387 11600 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\http.py", line 2396, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\http.py", line 1949, in _serve_db
    self.registry = Registry(self.db).check_signaling()
                    ^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 89, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 575, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo.tools.convert.ParseError: while parsing file:/d:/coding/seriously/learn-odoo/odoo/custom_addons/teknoparts_inventory/views/inherit_existing.xml:22
Error while validating view near:

<form string="Transfer" js_class="picking_form">
                <field name="country_code" invisible="1"/>
                <field name="is_locked" invisible="1"/>
                <field name="show_check_availability" invisible="1"/>
                <field name="show_lots_text" invisible="1"/>

Invalid modifier 'invisible': "x_is_qc_required = False or state != 'done'"
invalid syntax (<unknown>, line 1)

View error context:
{'file': 'd:\\coding\\seriously\\learn-odoo\\odoo\\custom_addons\\teknoparts_inventory\\views\\inherit_existing.xml',
 'line': 3,
 'name': 'stock.picking.form.inherit.qc',
 'view': ir.ui.view(1419,),
 'view.model': 'stock.picking',
 'view.parent': ir.ui.view(1063,),
 'xmlid': 'view_picking_form_inherit_qc'}

2025-09-15 03:15:20,389 11600 INFO ? werkzeug: 127.0.0.1 - - [15/Sep/2025 03:15:20] "GET /favicon.ico HTTP/1.1" 500 - 434 0.195 0.571
2025-09-15 03:16:23,822 11600 INFO ssi_odoo_db odoo.service.server: Initiating shutdown 
2025-09-15 03:16:23,823 11600 INFO ssi_odoo_db odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2025-09-15 03:16:23,978 11600 INFO ssi_odoo_db odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 3 connections  
